GET http://localhost:8080/api/v1/schedules/17 Nov 1995/
Accept: application/json

###
GET http://localhost:8080/api/v1/schedules
Accept: application/json

###
DELETE http://localhost:8080/api/v1/employees/abc@gmail.com/
Accept: application/json

{
"startDate": "1995-11-27T18:30:00.000+0000",
  "endDate": "1995-11-27T18:30:00.000+0000",
  "time": "15:00",
  "duration": 30,
  "repeat": true,
  "frequency": "Weekdays",
  "employee": null
}

###
POST http://localhost:8080/api/v1/employees/abc@gmail.com/
Content-Type: application/json

{
  "startDate": "1995-11-27T18:30:00.000+0000",
  "endDate": "1995-11-27T18:30:00.000+0000",
  "time": "15:00",
  "duration": 30,
  "repeat": true,
  "frequency": "Weekdays",
  "employee": null
}

###
POST http://localhost:8080/api/v1/employees/
Content-Type: application/json

{
  "id": 10,
  "mailId": "hello@mail.com",
  "patientId": "1",
  "schedules": [
    {
      "id": 10,
      "startDate": "1995-11-16T18:30:00.000+0000",
      "endDate": "1995-11-16T18:30:00.000+0000",
      "time": "10:00",
      "duration": 60,
      "repeat": false,
      "frequency": null
    },
    {
      "id": 20,
      "startDate": "2021-04-10T18:30:00.000+0000",
      "endDate": "2021-06-29T18:30:00.000+0000",
      "time": "10:00",
      "duration": 60,
      "repeat": true,
      "frequency": "Monthly"
    }
  ]
}

###
GET http://localhost:8080/api/v1/employees/abc@gmail.com/

###
GET http://localhost:8080/api/v1/employees/
Accept: application/json

